name: .NET Core

on:
  push:
    branches:
    - main
    - dev/*
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore .\PaymentGateway\PaymentGateway.sln
    - name: Build
      run: dotnet build .\PaymentGateway\PaymentGateway.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test .\PaymentGateway\PaymentGateway.sln --no-restore --verbosity normal
